-- ========================================
-- 项目名称：节拍数字工厂 · Takt Digital Factory (TDF)
-- 文件名称：menu_and_translation.sql
-- 功能描述：根据 IsGenMenu、IsGenTranslation 生成菜单、按钮菜单与翻译 SQL（IsGenMenu=1 生成页面菜单 menu_type=1 及子按钮 menu_type=2，IsGenTranslation=1 生成翻译）
-- 翻译表 language_id 从 takt_routine_i18n_language 按 culture_code 查询，顺序与 TaktLanguageSeedData 一致：英语、日语、韩语、简体中文、繁體中文（台湾）、繁體中文（香港）
-- ========================================

-- ---------- 菜单 SQL（IsGenMenu = 1 时生成） ----------
-- 表：Identity 库 takt_identity_menu（ConfigId=0 对应 identity_db）；id 为 SnowFlakeSingle.Instance.NextId() 生成
-- parent_id 来自表配置 ParentMenuId；create_by 为当前登录用户名（生成时传入，如 admin、user01）；create_time 为当前时间
INSERT INTO Takt_Identity_Dev.dbo.takt_identity_menu (
  id,  config_id,  menu_name,  menu_code,  menu_l10n_key,  parent_id,  path,  component,  menu_icon,  order_num,  menu_type,  permission,  is_visible,  is_cache,  is_external,  link_url,  menu_status,  create_by,  create_time,  is_deleted
) VALUES (
  2046836338816323584,
  '0',  N'工厂表',  'LOGISTICS_MATERIALS_PLANT',  'menu.logistics.materials.plant',  2046129984229216256,  N'/logistics/materials/plant',  N'logistics/materials/plant/index',  NULL,  0,  1,  N'logistics:materials:plant:list',  1,  0,  0,  NULL,  1,  N'admin',  GETDATE(),  0
);

-- 按钮菜单（MenuType=2，parent_id=上表页面菜单 id；permission 与生成控制器/前端一致，同权限去重）
INSERT INTO Takt_Identity_Dev.dbo.takt_identity_menu (
  id,  config_id,  menu_name,  menu_code,  menu_l10n_key,  parent_id,  path,  component,  menu_icon,  order_num,  menu_type,  permission,  is_visible,  is_cache,  is_external,  link_url,  menu_status,  create_by,  create_time,  is_deleted
) VALUES (
  2046836338984095744,  '0',  N'查询',  N'logistics_materials_plant_query',  N'common.button.query',  2046836338816323584,  NULL,  NULL,  NULL,  1,  2,  N'logistics:materials:plant:query',  1,  0,  0,  NULL,  1,  N'admin',  GETDATE(),  0
);
INSERT INTO Takt_Identity_Dev.dbo.takt_identity_menu (
  id,  config_id,  menu_name,  menu_code,  menu_l10n_key,  parent_id,  path,  component,  menu_icon,  order_num,  menu_type,  permission,  is_visible,  is_cache,  is_external,  link_url,  menu_status,  create_by,  create_time,  is_deleted
) VALUES (
  2046836338984095745,  '0',  N'新增',  N'logistics_materials_plant_create',  N'common.button.create',  2046836338816323584,  NULL,  NULL,  NULL,  2,  2,  N'logistics:materials:plant:create',  1,  0,  0,  NULL,  1,  N'admin',  GETDATE(),  0
);
INSERT INTO Takt_Identity_Dev.dbo.takt_identity_menu (
  id,  config_id,  menu_name,  menu_code,  menu_l10n_key,  parent_id,  path,  component,  menu_icon,  order_num,  menu_type,  permission,  is_visible,  is_cache,  is_external,  link_url,  menu_status,  create_by,  create_time,  is_deleted
) VALUES (
  2046836338984095746,  '0',  N'修改',  N'logistics_materials_plant_update',  N'common.button.update',  2046836338816323584,  NULL,  NULL,  NULL,  3,  2,  N'logistics:materials:plant:update',  1,  0,  0,  NULL,  1,  N'admin',  GETDATE(),  0
);
INSERT INTO Takt_Identity_Dev.dbo.takt_identity_menu (
  id,  config_id,  menu_name,  menu_code,  menu_l10n_key,  parent_id,  path,  component,  menu_icon,  order_num,  menu_type,  permission,  is_visible,  is_cache,  is_external,  link_url,  menu_status,  create_by,  create_time,  is_deleted
) VALUES (
  2046836338984095747,  '0',  N'删除',  N'logistics_materials_plant_delete',  N'common.button.delete',  2046836338816323584,  NULL,  NULL,  NULL,  4,  2,  N'logistics:materials:plant:delete',  1,  0,  0,  NULL,  1,  N'admin',  GETDATE(),  0
);
INSERT INTO Takt_Identity_Dev.dbo.takt_identity_menu (
  id,  config_id,  menu_name,  menu_code,  menu_l10n_key,  parent_id,  path,  component,  menu_icon,  order_num,  menu_type,  permission,  is_visible,  is_cache,  is_external,  link_url,  menu_status,  create_by,  create_time,  is_deleted
) VALUES (
  2046836338984095748,  '0',  N'导入',  N'logistics_materials_plant_import',  N'common.button.import',  2046836338816323584,  NULL,  NULL,  NULL,  5,  2,  N'logistics:materials:plant:import',  1,  0,  0,  NULL,  1,  N'admin',  GETDATE(),  0
);
INSERT INTO Takt_Identity_Dev.dbo.takt_identity_menu (
  id,  config_id,  menu_name,  menu_code,  menu_l10n_key,  parent_id,  path,  component,  menu_icon,  order_num,  menu_type,  permission,  is_visible,  is_cache,  is_external,  link_url,  menu_status,  create_by,  create_time,  is_deleted
) VALUES (
  2046836338984095749,  '0',  N'导出',  N'logistics_materials_plant_export',  N'common.button.export',  2046836338816323584,  NULL,  NULL,  NULL,  6,  2,  N'logistics:materials:plant:export',  1,  0,  0,  NULL,  1,  N'admin',  GETDATE(),  0
);
INSERT INTO Takt_Identity_Dev.dbo.takt_identity_menu (
  id,  config_id,  menu_name,  menu_code,  menu_l10n_key,  parent_id,  path,  component,  menu_icon,  order_num,  menu_type,  permission,  is_visible,  is_cache,  is_external,  link_url,  menu_status,  create_by,  create_time,  is_deleted
) VALUES (
  2046836338984095750,  '0',  N'模板',  N'logistics_materials_plant_template',  N'common.button.template',  2046836338816323584,  NULL,  NULL,  NULL,  7,  2,  N'logistics:materials:plant:template',  1,  0,  0,  NULL,  1,  N'admin',  GETDATE(),  0
);

-- ---------- 翻译 SQL（IsGenTranslation = 1 时生成） ----------
-- 表：Routine 库 takt_routine_i18n_translation（ConfigId=5 对应 routine_db）；id 为 SnowFlakeSingle.Instance.NextId() 生成，language_id 从 takt_routine_i18n_language 按 culture_code 查询
INSERT INTO Takt_Routine_Dev.dbo.takt_routine_i18n_translation (
  id,  config_id,  language_id,  culture_code,  resource_key,  translation_value,  resource_type,  resource_group,  order_num,  create_by,  create_time,  is_deleted
) VALUES
  (2046836338984095751, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'en-US' AND is_deleted = 0 AND config_id = N'5'), N'en-US', N'menu.logistics.materials.plant', N'工厂表', N'Frontend', N'menu', 0, N'admin', GETDATE(), 0)
  ,(2046836338984095752, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ja-JP' AND is_deleted = 0 AND config_id = N'5'), N'ja-JP', N'menu.logistics.materials.plant', N'工厂表', N'Frontend', N'menu', 0, N'admin', GETDATE(), 0)
  ,(2046836338984095753, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ko-KR' AND is_deleted = 0 AND config_id = N'5'), N'ko-KR', N'menu.logistics.materials.plant', N'工厂表', N'Frontend', N'menu', 0, N'admin', GETDATE(), 0)
  ,(2046836338984095754, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-CN' AND is_deleted = 0 AND config_id = N'5'), N'zh-CN', N'menu.logistics.materials.plant', N'工厂表管理', N'Frontend', N'menu', 0, N'admin', GETDATE(), 0)
  ,(2046836338984095755, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-TW' AND is_deleted = 0 AND config_id = N'5'), N'zh-TW', N'menu.logistics.materials.plant', N'工厂表', N'Frontend', N'menu', 0, N'admin', GETDATE(), 0)
  ,(2046836338984095756, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-HK' AND is_deleted = 0 AND config_id = N'5'), N'zh-HK', N'menu.logistics.materials.plant', N'工厂表', N'Frontend', N'menu', 0, N'admin', GETDATE(), 0)
  ,(2046836338984095757, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'en-US' AND is_deleted = 0 AND config_id = N'5'), N'en-US', N'logistics.materials.plant.entities.plantcode', N'工厂代码', N'Frontend', N'page', 1, N'admin', GETDATE(), 0)
  ,(2046836338984095758, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ja-JP' AND is_deleted = 0 AND config_id = N'5'), N'ja-JP', N'logistics.materials.plant.entities.plantcode', N'工厂代码', N'Frontend', N'page', 1, N'admin', GETDATE(), 0)
  ,(2046836338984095759, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ko-KR' AND is_deleted = 0 AND config_id = N'5'), N'ko-KR', N'logistics.materials.plant.entities.plantcode', N'工厂代码', N'Frontend', N'page', 1, N'admin', GETDATE(), 0)
  ,(2046836338984095760, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-CN' AND is_deleted = 0 AND config_id = N'5'), N'zh-CN', N'logistics.materials.plant.entities.plantcode', N'工厂代码', N'Frontend', N'page', 1, N'admin', GETDATE(), 0)
  ,(2046836338984095761, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-TW' AND is_deleted = 0 AND config_id = N'5'), N'zh-TW', N'logistics.materials.plant.entities.plantcode', N'工厂代码', N'Frontend', N'page', 1, N'admin', GETDATE(), 0)
  ,(2046836338984095762, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-HK' AND is_deleted = 0 AND config_id = N'5'), N'zh-HK', N'logistics.materials.plant.entities.plantcode', N'工厂代码', N'Frontend', N'page', 1, N'admin', GETDATE(), 0)
  ,(2046836338984095763, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'en-US' AND is_deleted = 0 AND config_id = N'5'), N'en-US', N'logistics.materials.plant.entities.plantname', N'工厂名称', N'Frontend', N'page', 2, N'admin', GETDATE(), 0)
  ,(2046836338984095764, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ja-JP' AND is_deleted = 0 AND config_id = N'5'), N'ja-JP', N'logistics.materials.plant.entities.plantname', N'工厂名称', N'Frontend', N'page', 2, N'admin', GETDATE(), 0)
  ,(2046836338984095765, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ko-KR' AND is_deleted = 0 AND config_id = N'5'), N'ko-KR', N'logistics.materials.plant.entities.plantname', N'工厂名称', N'Frontend', N'page', 2, N'admin', GETDATE(), 0)
  ,(2046836338984095766, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-CN' AND is_deleted = 0 AND config_id = N'5'), N'zh-CN', N'logistics.materials.plant.entities.plantname', N'工厂名称', N'Frontend', N'page', 2, N'admin', GETDATE(), 0)
  ,(2046836338984095767, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-TW' AND is_deleted = 0 AND config_id = N'5'), N'zh-TW', N'logistics.materials.plant.entities.plantname', N'工厂名称', N'Frontend', N'page', 2, N'admin', GETDATE(), 0)
  ,(2046836338984095768, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-HK' AND is_deleted = 0 AND config_id = N'5'), N'zh-HK', N'logistics.materials.plant.entities.plantname', N'工厂名称', N'Frontend', N'page', 2, N'admin', GETDATE(), 0)
  ,(2046836338984095769, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'en-US' AND is_deleted = 0 AND config_id = N'5'), N'en-US', N'logistics.materials.plant.entities.plantshortname', N'工厂简称', N'Frontend', N'page', 3, N'admin', GETDATE(), 0)
  ,(2046836338984095770, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ja-JP' AND is_deleted = 0 AND config_id = N'5'), N'ja-JP', N'logistics.materials.plant.entities.plantshortname', N'工厂简称', N'Frontend', N'page', 3, N'admin', GETDATE(), 0)
  ,(2046836338984095771, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ko-KR' AND is_deleted = 0 AND config_id = N'5'), N'ko-KR', N'logistics.materials.plant.entities.plantshortname', N'工厂简称', N'Frontend', N'page', 3, N'admin', GETDATE(), 0)
  ,(2046836338984095772, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-CN' AND is_deleted = 0 AND config_id = N'5'), N'zh-CN', N'logistics.materials.plant.entities.plantshortname', N'工厂简称', N'Frontend', N'page', 3, N'admin', GETDATE(), 0)
  ,(2046836338984095773, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-TW' AND is_deleted = 0 AND config_id = N'5'), N'zh-TW', N'logistics.materials.plant.entities.plantshortname', N'工厂简称', N'Frontend', N'page', 3, N'admin', GETDATE(), 0)
  ,(2046836338984095774, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-HK' AND is_deleted = 0 AND config_id = N'5'), N'zh-HK', N'logistics.materials.plant.entities.plantshortname', N'工厂简称', N'Frontend', N'page', 3, N'admin', GETDATE(), 0)
  ,(2046836338984095775, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'en-US' AND is_deleted = 0 AND config_id = N'5'), N'en-US', N'logistics.materials.plant.entities.registrationaddress', N'注册地址', N'Frontend', N'page', 4, N'admin', GETDATE(), 0)
  ,(2046836338984095776, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ja-JP' AND is_deleted = 0 AND config_id = N'5'), N'ja-JP', N'logistics.materials.plant.entities.registrationaddress', N'注册地址', N'Frontend', N'page', 4, N'admin', GETDATE(), 0)
  ,(2046836338984095777, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ko-KR' AND is_deleted = 0 AND config_id = N'5'), N'ko-KR', N'logistics.materials.plant.entities.registrationaddress', N'注册地址', N'Frontend', N'page', 4, N'admin', GETDATE(), 0)
  ,(2046836338984095778, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-CN' AND is_deleted = 0 AND config_id = N'5'), N'zh-CN', N'logistics.materials.plant.entities.registrationaddress', N'注册地址', N'Frontend', N'page', 4, N'admin', GETDATE(), 0)
  ,(2046836338984095779, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-TW' AND is_deleted = 0 AND config_id = N'5'), N'zh-TW', N'logistics.materials.plant.entities.registrationaddress', N'注册地址', N'Frontend', N'page', 4, N'admin', GETDATE(), 0)
  ,(2046836338984095780, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-HK' AND is_deleted = 0 AND config_id = N'5'), N'zh-HK', N'logistics.materials.plant.entities.registrationaddress', N'注册地址', N'Frontend', N'page', 4, N'admin', GETDATE(), 0)
  ,(2046836338984095781, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'en-US' AND is_deleted = 0 AND config_id = N'5'), N'en-US', N'logistics.materials.plant.entities.registrationregion', N'注册地区-国家', N'Frontend', N'page', 5, N'admin', GETDATE(), 0)
  ,(2046836338984095782, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ja-JP' AND is_deleted = 0 AND config_id = N'5'), N'ja-JP', N'logistics.materials.plant.entities.registrationregion', N'注册地区-国家', N'Frontend', N'page', 5, N'admin', GETDATE(), 0)
  ,(2046836338984095783, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ko-KR' AND is_deleted = 0 AND config_id = N'5'), N'ko-KR', N'logistics.materials.plant.entities.registrationregion', N'注册地区-国家', N'Frontend', N'page', 5, N'admin', GETDATE(), 0)
  ,(2046836338984095784, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-CN' AND is_deleted = 0 AND config_id = N'5'), N'zh-CN', N'logistics.materials.plant.entities.registrationregion', N'注册地区-国家', N'Frontend', N'page', 5, N'admin', GETDATE(), 0)
  ,(2046836338984095785, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-TW' AND is_deleted = 0 AND config_id = N'5'), N'zh-TW', N'logistics.materials.plant.entities.registrationregion', N'注册地区-国家', N'Frontend', N'page', 5, N'admin', GETDATE(), 0)
  ,(2046836338984095786, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-HK' AND is_deleted = 0 AND config_id = N'5'), N'zh-HK', N'logistics.materials.plant.entities.registrationregion', N'注册地区-国家', N'Frontend', N'page', 5, N'admin', GETDATE(), 0)
  ,(2046836338984095787, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'en-US' AND is_deleted = 0 AND config_id = N'5'), N'en-US', N'logistics.materials.plant.entities.registrationprovince', N'注册地区-省', N'Frontend', N'page', 6, N'admin', GETDATE(), 0)
  ,(2046836338984095788, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ja-JP' AND is_deleted = 0 AND config_id = N'5'), N'ja-JP', N'logistics.materials.plant.entities.registrationprovince', N'注册地区-省', N'Frontend', N'page', 6, N'admin', GETDATE(), 0)
  ,(2046836338984095789, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ko-KR' AND is_deleted = 0 AND config_id = N'5'), N'ko-KR', N'logistics.materials.plant.entities.registrationprovince', N'注册地区-省', N'Frontend', N'page', 6, N'admin', GETDATE(), 0)
  ,(2046836338984095790, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-CN' AND is_deleted = 0 AND config_id = N'5'), N'zh-CN', N'logistics.materials.plant.entities.registrationprovince', N'注册地区-省', N'Frontend', N'page', 6, N'admin', GETDATE(), 0)
  ,(2046836338984095791, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-TW' AND is_deleted = 0 AND config_id = N'5'), N'zh-TW', N'logistics.materials.plant.entities.registrationprovince', N'注册地区-省', N'Frontend', N'page', 6, N'admin', GETDATE(), 0)
  ,(2046836338984095792, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-HK' AND is_deleted = 0 AND config_id = N'5'), N'zh-HK', N'logistics.materials.plant.entities.registrationprovince', N'注册地区-省', N'Frontend', N'page', 6, N'admin', GETDATE(), 0)
  ,(2046836338984095793, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'en-US' AND is_deleted = 0 AND config_id = N'5'), N'en-US', N'logistics.materials.plant.entities.registrationcity', N'注册地区-市', N'Frontend', N'page', 7, N'admin', GETDATE(), 0)
  ,(2046836338984095794, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ja-JP' AND is_deleted = 0 AND config_id = N'5'), N'ja-JP', N'logistics.materials.plant.entities.registrationcity', N'注册地区-市', N'Frontend', N'page', 7, N'admin', GETDATE(), 0)
  ,(2046836338984095795, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ko-KR' AND is_deleted = 0 AND config_id = N'5'), N'ko-KR', N'logistics.materials.plant.entities.registrationcity', N'注册地区-市', N'Frontend', N'page', 7, N'admin', GETDATE(), 0)
  ,(2046836338984095796, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-CN' AND is_deleted = 0 AND config_id = N'5'), N'zh-CN', N'logistics.materials.plant.entities.registrationcity', N'注册地区-市', N'Frontend', N'page', 7, N'admin', GETDATE(), 0)
  ,(2046836338984095797, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-TW' AND is_deleted = 0 AND config_id = N'5'), N'zh-TW', N'logistics.materials.plant.entities.registrationcity', N'注册地区-市', N'Frontend', N'page', 7, N'admin', GETDATE(), 0)
  ,(2046836338984095798, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-HK' AND is_deleted = 0 AND config_id = N'5'), N'zh-HK', N'logistics.materials.plant.entities.registrationcity', N'注册地区-市', N'Frontend', N'page', 7, N'admin', GETDATE(), 0)
  ,(2046836338984095799, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'en-US' AND is_deleted = 0 AND config_id = N'5'), N'en-US', N'logistics.materials.plant.entities.businessregion', N'经营地区-国家', N'Frontend', N'page', 8, N'admin', GETDATE(), 0)
  ,(2046836338984095800, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ja-JP' AND is_deleted = 0 AND config_id = N'5'), N'ja-JP', N'logistics.materials.plant.entities.businessregion', N'经营地区-国家', N'Frontend', N'page', 8, N'admin', GETDATE(), 0)
  ,(2046836338984095801, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ko-KR' AND is_deleted = 0 AND config_id = N'5'), N'ko-KR', N'logistics.materials.plant.entities.businessregion', N'经营地区-国家', N'Frontend', N'page', 8, N'admin', GETDATE(), 0)
  ,(2046836338984095802, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-CN' AND is_deleted = 0 AND config_id = N'5'), N'zh-CN', N'logistics.materials.plant.entities.businessregion', N'经营地区-国家', N'Frontend', N'page', 8, N'admin', GETDATE(), 0)
  ,(2046836338984095803, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-TW' AND is_deleted = 0 AND config_id = N'5'), N'zh-TW', N'logistics.materials.plant.entities.businessregion', N'经营地区-国家', N'Frontend', N'page', 8, N'admin', GETDATE(), 0)
  ,(2046836338984095804, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-HK' AND is_deleted = 0 AND config_id = N'5'), N'zh-HK', N'logistics.materials.plant.entities.businessregion', N'经营地区-国家', N'Frontend', N'page', 8, N'admin', GETDATE(), 0)
  ,(2046836338984095805, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'en-US' AND is_deleted = 0 AND config_id = N'5'), N'en-US', N'logistics.materials.plant.entities.businessprovince', N'经营地区-省', N'Frontend', N'page', 9, N'admin', GETDATE(), 0)
  ,(2046836338984095806, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ja-JP' AND is_deleted = 0 AND config_id = N'5'), N'ja-JP', N'logistics.materials.plant.entities.businessprovince', N'经营地区-省', N'Frontend', N'page', 9, N'admin', GETDATE(), 0)
  ,(2046836338984095807, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ko-KR' AND is_deleted = 0 AND config_id = N'5'), N'ko-KR', N'logistics.materials.plant.entities.businessprovince', N'经营地区-省', N'Frontend', N'page', 9, N'admin', GETDATE(), 0)
  ,(2046836338984095808, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-CN' AND is_deleted = 0 AND config_id = N'5'), N'zh-CN', N'logistics.materials.plant.entities.businessprovince', N'经营地区-省', N'Frontend', N'page', 9, N'admin', GETDATE(), 0)
  ,(2046836338984095809, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-TW' AND is_deleted = 0 AND config_id = N'5'), N'zh-TW', N'logistics.materials.plant.entities.businessprovince', N'经营地区-省', N'Frontend', N'page', 9, N'admin', GETDATE(), 0)
  ,(2046836338984095810, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-HK' AND is_deleted = 0 AND config_id = N'5'), N'zh-HK', N'logistics.materials.plant.entities.businessprovince', N'经营地区-省', N'Frontend', N'page', 9, N'admin', GETDATE(), 0)
  ,(2046836338984095811, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'en-US' AND is_deleted = 0 AND config_id = N'5'), N'en-US', N'logistics.materials.plant.entities.businesscity', N'经营地区-市', N'Frontend', N'page', 10, N'admin', GETDATE(), 0)
  ,(2046836338984095812, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ja-JP' AND is_deleted = 0 AND config_id = N'5'), N'ja-JP', N'logistics.materials.plant.entities.businesscity', N'经营地区-市', N'Frontend', N'page', 10, N'admin', GETDATE(), 0)
  ,(2046836338984095813, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ko-KR' AND is_deleted = 0 AND config_id = N'5'), N'ko-KR', N'logistics.materials.plant.entities.businesscity', N'经营地区-市', N'Frontend', N'page', 10, N'admin', GETDATE(), 0)
  ,(2046836338984095814, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-CN' AND is_deleted = 0 AND config_id = N'5'), N'zh-CN', N'logistics.materials.plant.entities.businesscity', N'经营地区-市', N'Frontend', N'page', 10, N'admin', GETDATE(), 0)
  ,(2046836338984095815, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-TW' AND is_deleted = 0 AND config_id = N'5'), N'zh-TW', N'logistics.materials.plant.entities.businesscity', N'经营地区-市', N'Frontend', N'page', 10, N'admin', GETDATE(), 0)
  ,(2046836338984095816, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-HK' AND is_deleted = 0 AND config_id = N'5'), N'zh-HK', N'logistics.materials.plant.entities.businesscity', N'经营地区-市', N'Frontend', N'page', 10, N'admin', GETDATE(), 0)
  ,(2046836338984095817, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'en-US' AND is_deleted = 0 AND config_id = N'5'), N'en-US', N'logistics.materials.plant.entities.businessaddress', N'经营地址', N'Frontend', N'page', 11, N'admin', GETDATE(), 0)
  ,(2046836338984095818, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ja-JP' AND is_deleted = 0 AND config_id = N'5'), N'ja-JP', N'logistics.materials.plant.entities.businessaddress', N'经营地址', N'Frontend', N'page', 11, N'admin', GETDATE(), 0)
  ,(2046836338984095819, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ko-KR' AND is_deleted = 0 AND config_id = N'5'), N'ko-KR', N'logistics.materials.plant.entities.businessaddress', N'经营地址', N'Frontend', N'page', 11, N'admin', GETDATE(), 0)
  ,(2046836338984095820, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-CN' AND is_deleted = 0 AND config_id = N'5'), N'zh-CN', N'logistics.materials.plant.entities.businessaddress', N'经营地址', N'Frontend', N'page', 11, N'admin', GETDATE(), 0)
  ,(2046836338984095821, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-TW' AND is_deleted = 0 AND config_id = N'5'), N'zh-TW', N'logistics.materials.plant.entities.businessaddress', N'经营地址', N'Frontend', N'page', 11, N'admin', GETDATE(), 0)
  ,(2046836338984095822, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-HK' AND is_deleted = 0 AND config_id = N'5'), N'zh-HK', N'logistics.materials.plant.entities.businessaddress', N'经营地址', N'Frontend', N'page', 11, N'admin', GETDATE(), 0)
  ,(2046836338984095823, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'en-US' AND is_deleted = 0 AND config_id = N'5'), N'en-US', N'logistics.materials.plant.entities.plantaddress', N'工厂地址', N'Frontend', N'page', 12, N'admin', GETDATE(), 0)
  ,(2046836338984095824, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ja-JP' AND is_deleted = 0 AND config_id = N'5'), N'ja-JP', N'logistics.materials.plant.entities.plantaddress', N'工厂地址', N'Frontend', N'page', 12, N'admin', GETDATE(), 0)
  ,(2046836338984095825, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ko-KR' AND is_deleted = 0 AND config_id = N'5'), N'ko-KR', N'logistics.materials.plant.entities.plantaddress', N'工厂地址', N'Frontend', N'page', 12, N'admin', GETDATE(), 0)
  ,(2046836338984095826, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-CN' AND is_deleted = 0 AND config_id = N'5'), N'zh-CN', N'logistics.materials.plant.entities.plantaddress', N'工厂地址', N'Frontend', N'page', 12, N'admin', GETDATE(), 0)
  ,(2046836338984095827, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-TW' AND is_deleted = 0 AND config_id = N'5'), N'zh-TW', N'logistics.materials.plant.entities.plantaddress', N'工厂地址', N'Frontend', N'page', 12, N'admin', GETDATE(), 0)
  ,(2046836338984095828, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-HK' AND is_deleted = 0 AND config_id = N'5'), N'zh-HK', N'logistics.materials.plant.entities.plantaddress', N'工厂地址', N'Frontend', N'page', 12, N'admin', GETDATE(), 0)
  ,(2046836338984095829, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'en-US' AND is_deleted = 0 AND config_id = N'5'), N'en-US', N'logistics.materials.plant.entities.plantphone', N'工厂电话', N'Frontend', N'page', 13, N'admin', GETDATE(), 0)
  ,(2046836338984095830, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ja-JP' AND is_deleted = 0 AND config_id = N'5'), N'ja-JP', N'logistics.materials.plant.entities.plantphone', N'工厂电话', N'Frontend', N'page', 13, N'admin', GETDATE(), 0)
  ,(2046836338984095831, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ko-KR' AND is_deleted = 0 AND config_id = N'5'), N'ko-KR', N'logistics.materials.plant.entities.plantphone', N'工厂电话', N'Frontend', N'page', 13, N'admin', GETDATE(), 0)
  ,(2046836338984095832, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-CN' AND is_deleted = 0 AND config_id = N'5'), N'zh-CN', N'logistics.materials.plant.entities.plantphone', N'工厂电话', N'Frontend', N'page', 13, N'admin', GETDATE(), 0)
  ,(2046836338984095833, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-TW' AND is_deleted = 0 AND config_id = N'5'), N'zh-TW', N'logistics.materials.plant.entities.plantphone', N'工厂电话', N'Frontend', N'page', 13, N'admin', GETDATE(), 0)
  ,(2046836338984095834, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-HK' AND is_deleted = 0 AND config_id = N'5'), N'zh-HK', N'logistics.materials.plant.entities.plantphone', N'工厂电话', N'Frontend', N'page', 13, N'admin', GETDATE(), 0)
  ,(2046836338984095835, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'en-US' AND is_deleted = 0 AND config_id = N'5'), N'en-US', N'logistics.materials.plant.entities.plantemail', N'工厂邮箱', N'Frontend', N'page', 14, N'admin', GETDATE(), 0)
  ,(2046836338984095836, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ja-JP' AND is_deleted = 0 AND config_id = N'5'), N'ja-JP', N'logistics.materials.plant.entities.plantemail', N'工厂邮箱', N'Frontend', N'page', 14, N'admin', GETDATE(), 0)
  ,(2046836338984095837, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ko-KR' AND is_deleted = 0 AND config_id = N'5'), N'ko-KR', N'logistics.materials.plant.entities.plantemail', N'工厂邮箱', N'Frontend', N'page', 14, N'admin', GETDATE(), 0)
  ,(2046836338984095838, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-CN' AND is_deleted = 0 AND config_id = N'5'), N'zh-CN', N'logistics.materials.plant.entities.plantemail', N'工厂邮箱', N'Frontend', N'page', 14, N'admin', GETDATE(), 0)
  ,(2046836338984095839, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-TW' AND is_deleted = 0 AND config_id = N'5'), N'zh-TW', N'logistics.materials.plant.entities.plantemail', N'工厂邮箱', N'Frontend', N'page', 14, N'admin', GETDATE(), 0)
  ,(2046836338984095840, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-HK' AND is_deleted = 0 AND config_id = N'5'), N'zh-HK', N'logistics.materials.plant.entities.plantemail', N'工厂邮箱', N'Frontend', N'page', 14, N'admin', GETDATE(), 0)
  ,(2046836338984095841, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'en-US' AND is_deleted = 0 AND config_id = N'5'), N'en-US', N'logistics.materials.plant.entities.plantmanager', N'工厂负责人', N'Frontend', N'page', 15, N'admin', GETDATE(), 0)
  ,(2046836338984095842, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ja-JP' AND is_deleted = 0 AND config_id = N'5'), N'ja-JP', N'logistics.materials.plant.entities.plantmanager', N'工厂负责人', N'Frontend', N'page', 15, N'admin', GETDATE(), 0)
  ,(2046836338984095843, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ko-KR' AND is_deleted = 0 AND config_id = N'5'), N'ko-KR', N'logistics.materials.plant.entities.plantmanager', N'工厂负责人', N'Frontend', N'page', 15, N'admin', GETDATE(), 0)
  ,(2046836338984095844, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-CN' AND is_deleted = 0 AND config_id = N'5'), N'zh-CN', N'logistics.materials.plant.entities.plantmanager', N'工厂负责人', N'Frontend', N'page', 15, N'admin', GETDATE(), 0)
  ,(2046836338984095845, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-TW' AND is_deleted = 0 AND config_id = N'5'), N'zh-TW', N'logistics.materials.plant.entities.plantmanager', N'工厂负责人', N'Frontend', N'page', 15, N'admin', GETDATE(), 0)
  ,(2046836338984095846, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-HK' AND is_deleted = 0 AND config_id = N'5'), N'zh-HK', N'logistics.materials.plant.entities.plantmanager', N'工厂负责人', N'Frontend', N'page', 15, N'admin', GETDATE(), 0)
  ,(2046836338984095847, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'en-US' AND is_deleted = 0 AND config_id = N'5'), N'en-US', N'logistics.materials.plant.entities.enterprisenature', N'企业性质', N'Frontend', N'page', 16, N'admin', GETDATE(), 0)
  ,(2046836338984095848, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ja-JP' AND is_deleted = 0 AND config_id = N'5'), N'ja-JP', N'logistics.materials.plant.entities.enterprisenature', N'企业性质', N'Frontend', N'page', 16, N'admin', GETDATE(), 0)
  ,(2046836338984095849, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ko-KR' AND is_deleted = 0 AND config_id = N'5'), N'ko-KR', N'logistics.materials.plant.entities.enterprisenature', N'企业性质', N'Frontend', N'page', 16, N'admin', GETDATE(), 0)
  ,(2046836338984095850, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-CN' AND is_deleted = 0 AND config_id = N'5'), N'zh-CN', N'logistics.materials.plant.entities.enterprisenature', N'企业性质', N'Frontend', N'page', 16, N'admin', GETDATE(), 0)
  ,(2046836338984095851, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-TW' AND is_deleted = 0 AND config_id = N'5'), N'zh-TW', N'logistics.materials.plant.entities.enterprisenature', N'企业性质', N'Frontend', N'page', 16, N'admin', GETDATE(), 0)
  ,(2046836338984095852, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-HK' AND is_deleted = 0 AND config_id = N'5'), N'zh-HK', N'logistics.materials.plant.entities.enterprisenature', N'企业性质', N'Frontend', N'page', 16, N'admin', GETDATE(), 0)
  ,(2046836338984095853, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'en-US' AND is_deleted = 0 AND config_id = N'5'), N'en-US', N'logistics.materials.plant.entities.industryattribute', N'行业属性', N'Frontend', N'page', 17, N'admin', GETDATE(), 0)
  ,(2046836338984095854, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ja-JP' AND is_deleted = 0 AND config_id = N'5'), N'ja-JP', N'logistics.materials.plant.entities.industryattribute', N'行业属性', N'Frontend', N'page', 17, N'admin', GETDATE(), 0)
  ,(2046836338984095855, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ko-KR' AND is_deleted = 0 AND config_id = N'5'), N'ko-KR', N'logistics.materials.plant.entities.industryattribute', N'行业属性', N'Frontend', N'page', 17, N'admin', GETDATE(), 0)
  ,(2046836338984095856, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-CN' AND is_deleted = 0 AND config_id = N'5'), N'zh-CN', N'logistics.materials.plant.entities.industryattribute', N'行业属性', N'Frontend', N'page', 17, N'admin', GETDATE(), 0)
  ,(2046836338984095857, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-TW' AND is_deleted = 0 AND config_id = N'5'), N'zh-TW', N'logistics.materials.plant.entities.industryattribute', N'行业属性', N'Frontend', N'page', 17, N'admin', GETDATE(), 0)
  ,(2046836338984095858, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-HK' AND is_deleted = 0 AND config_id = N'5'), N'zh-HK', N'logistics.materials.plant.entities.industryattribute', N'行业属性', N'Frontend', N'page', 17, N'admin', GETDATE(), 0)
  ,(2046836338984095859, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'en-US' AND is_deleted = 0 AND config_id = N'5'), N'en-US', N'logistics.materials.plant.entities.enterprisescale', N'企业规模', N'Frontend', N'page', 18, N'admin', GETDATE(), 0)
  ,(2046836338984095860, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ja-JP' AND is_deleted = 0 AND config_id = N'5'), N'ja-JP', N'logistics.materials.plant.entities.enterprisescale', N'企业规模', N'Frontend', N'page', 18, N'admin', GETDATE(), 0)
  ,(2046836338984095861, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ko-KR' AND is_deleted = 0 AND config_id = N'5'), N'ko-KR', N'logistics.materials.plant.entities.enterprisescale', N'企业规模', N'Frontend', N'page', 18, N'admin', GETDATE(), 0)
  ,(2046836338984095862, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-CN' AND is_deleted = 0 AND config_id = N'5'), N'zh-CN', N'logistics.materials.plant.entities.enterprisescale', N'企业规模', N'Frontend', N'page', 18, N'admin', GETDATE(), 0)
  ,(2046836338984095863, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-TW' AND is_deleted = 0 AND config_id = N'5'), N'zh-TW', N'logistics.materials.plant.entities.enterprisescale', N'企业规模', N'Frontend', N'page', 18, N'admin', GETDATE(), 0)
  ,(2046836338984095864, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-HK' AND is_deleted = 0 AND config_id = N'5'), N'zh-HK', N'logistics.materials.plant.entities.enterprisescale', N'企业规模', N'Frontend', N'page', 18, N'admin', GETDATE(), 0)
  ,(2046836338984095865, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'en-US' AND is_deleted = 0 AND config_id = N'5'), N'en-US', N'logistics.materials.plant.entities.businessscope', N'经营范围', N'Frontend', N'page', 19, N'admin', GETDATE(), 0)
  ,(2046836338984095866, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ja-JP' AND is_deleted = 0 AND config_id = N'5'), N'ja-JP', N'logistics.materials.plant.entities.businessscope', N'经营范围', N'Frontend', N'page', 19, N'admin', GETDATE(), 0)
  ,(2046836338984095867, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ko-KR' AND is_deleted = 0 AND config_id = N'5'), N'ko-KR', N'logistics.materials.plant.entities.businessscope', N'经营范围', N'Frontend', N'page', 19, N'admin', GETDATE(), 0)
  ,(2046836338984095868, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-CN' AND is_deleted = 0 AND config_id = N'5'), N'zh-CN', N'logistics.materials.plant.entities.businessscope', N'经营范围', N'Frontend', N'page', 19, N'admin', GETDATE(), 0)
  ,(2046836338984095869, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-TW' AND is_deleted = 0 AND config_id = N'5'), N'zh-TW', N'logistics.materials.plant.entities.businessscope', N'经营范围', N'Frontend', N'page', 19, N'admin', GETDATE(), 0)
  ,(2046836338984095870, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-HK' AND is_deleted = 0 AND config_id = N'5'), N'zh-HK', N'logistics.materials.plant.entities.businessscope', N'经营范围', N'Frontend', N'page', 19, N'admin', GETDATE(), 0)
  ,(2046836338984095871, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'en-US' AND is_deleted = 0 AND config_id = N'5'), N'en-US', N'logistics.materials.plant.entities.relatedcompany', N'关联公司', N'Frontend', N'page', 20, N'admin', GETDATE(), 0)
  ,(2046836338984095872, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ja-JP' AND is_deleted = 0 AND config_id = N'5'), N'ja-JP', N'logistics.materials.plant.entities.relatedcompany', N'关联公司', N'Frontend', N'page', 20, N'admin', GETDATE(), 0)
  ,(2046836338984095873, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ko-KR' AND is_deleted = 0 AND config_id = N'5'), N'ko-KR', N'logistics.materials.plant.entities.relatedcompany', N'关联公司', N'Frontend', N'page', 20, N'admin', GETDATE(), 0)
  ,(2046836338984095874, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-CN' AND is_deleted = 0 AND config_id = N'5'), N'zh-CN', N'logistics.materials.plant.entities.relatedcompany', N'关联公司', N'Frontend', N'page', 20, N'admin', GETDATE(), 0)
  ,(2046836338984095875, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-TW' AND is_deleted = 0 AND config_id = N'5'), N'zh-TW', N'logistics.materials.plant.entities.relatedcompany', N'关联公司', N'Frontend', N'page', 20, N'admin', GETDATE(), 0)
  ,(2046836338984095876, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-HK' AND is_deleted = 0 AND config_id = N'5'), N'zh-HK', N'logistics.materials.plant.entities.relatedcompany', N'关联公司', N'Frontend', N'page', 20, N'admin', GETDATE(), 0)
  ,(2046836338984095877, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'en-US' AND is_deleted = 0 AND config_id = N'5'), N'en-US', N'logistics.materials.plant.entities.plantstatus', N'工厂状态', N'Frontend', N'page', 21, N'admin', GETDATE(), 0)
  ,(2046836338984095878, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ja-JP' AND is_deleted = 0 AND config_id = N'5'), N'ja-JP', N'logistics.materials.plant.entities.plantstatus', N'工厂状态', N'Frontend', N'page', 21, N'admin', GETDATE(), 0)
  ,(2046836338984095879, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ko-KR' AND is_deleted = 0 AND config_id = N'5'), N'ko-KR', N'logistics.materials.plant.entities.plantstatus', N'工厂状态', N'Frontend', N'page', 21, N'admin', GETDATE(), 0)
  ,(2046836338984095880, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-CN' AND is_deleted = 0 AND config_id = N'5'), N'zh-CN', N'logistics.materials.plant.entities.plantstatus', N'工厂状态', N'Frontend', N'page', 21, N'admin', GETDATE(), 0)
  ,(2046836338984095881, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-TW' AND is_deleted = 0 AND config_id = N'5'), N'zh-TW', N'logistics.materials.plant.entities.plantstatus', N'工厂状态', N'Frontend', N'page', 21, N'admin', GETDATE(), 0)
  ,(2046836338984095882, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-HK' AND is_deleted = 0 AND config_id = N'5'), N'zh-HK', N'logistics.materials.plant.entities.plantstatus', N'工厂状态', N'Frontend', N'page', 21, N'admin', GETDATE(), 0)
  ,(2046836338984095883, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'en-US' AND is_deleted = 0 AND config_id = N'5'), N'en-US', N'logistics.materials.plant.entities.ordernum', N'排序号', N'Frontend', N'page', 22, N'admin', GETDATE(), 0)
  ,(2046836338984095884, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ja-JP' AND is_deleted = 0 AND config_id = N'5'), N'ja-JP', N'logistics.materials.plant.entities.ordernum', N'排序号', N'Frontend', N'page', 22, N'admin', GETDATE(), 0)
  ,(2046836338984095885, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ko-KR' AND is_deleted = 0 AND config_id = N'5'), N'ko-KR', N'logistics.materials.plant.entities.ordernum', N'排序号', N'Frontend', N'page', 22, N'admin', GETDATE(), 0)
  ,(2046836338984095886, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-CN' AND is_deleted = 0 AND config_id = N'5'), N'zh-CN', N'logistics.materials.plant.entities.ordernum', N'排序号', N'Frontend', N'page', 22, N'admin', GETDATE(), 0)
  ,(2046836338984095887, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-TW' AND is_deleted = 0 AND config_id = N'5'), N'zh-TW', N'logistics.materials.plant.entities.ordernum', N'排序号', N'Frontend', N'page', 22, N'admin', GETDATE(), 0)
  ,(2046836338984095888, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-HK' AND is_deleted = 0 AND config_id = N'5'), N'zh-HK', N'logistics.materials.plant.entities.ordernum', N'排序号', N'Frontend', N'page', 22, N'admin', GETDATE(), 0)
  ,(2046836338984095889, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'en-US' AND is_deleted = 0 AND config_id = N'5'), N'en-US', N'logistics.materials.plant.entities.extfieldjson', N'扩展字段JSON', N'Frontend', N'page', 23, N'admin', GETDATE(), 0)
  ,(2046836338984095890, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ja-JP' AND is_deleted = 0 AND config_id = N'5'), N'ja-JP', N'logistics.materials.plant.entities.extfieldjson', N'扩展字段JSON', N'Frontend', N'page', 23, N'admin', GETDATE(), 0)
  ,(2046836338984095891, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ko-KR' AND is_deleted = 0 AND config_id = N'5'), N'ko-KR', N'logistics.materials.plant.entities.extfieldjson', N'扩展字段JSON', N'Frontend', N'page', 23, N'admin', GETDATE(), 0)
  ,(2046836338984095892, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-CN' AND is_deleted = 0 AND config_id = N'5'), N'zh-CN', N'logistics.materials.plant.entities.extfieldjson', N'扩展字段JSON', N'Frontend', N'page', 23, N'admin', GETDATE(), 0)
  ,(2046836338984095893, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-TW' AND is_deleted = 0 AND config_id = N'5'), N'zh-TW', N'logistics.materials.plant.entities.extfieldjson', N'扩展字段JSON', N'Frontend', N'page', 23, N'admin', GETDATE(), 0)
  ,(2046836338984095894, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-HK' AND is_deleted = 0 AND config_id = N'5'), N'zh-HK', N'logistics.materials.plant.entities.extfieldjson', N'扩展字段JSON', N'Frontend', N'page', 23, N'admin', GETDATE(), 0)
  ,(2046836338984095895, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'en-US' AND is_deleted = 0 AND config_id = N'5'), N'en-US', N'logistics.materials.plant.entities.remark', N'备注', N'Frontend', N'page', 24, N'admin', GETDATE(), 0)
  ,(2046836338984095896, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ja-JP' AND is_deleted = 0 AND config_id = N'5'), N'ja-JP', N'logistics.materials.plant.entities.remark', N'备注', N'Frontend', N'page', 24, N'admin', GETDATE(), 0)
  ,(2046836338984095897, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'ko-KR' AND is_deleted = 0 AND config_id = N'5'), N'ko-KR', N'logistics.materials.plant.entities.remark', N'备注', N'Frontend', N'page', 24, N'admin', GETDATE(), 0)
  ,(2046836338984095898, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-CN' AND is_deleted = 0 AND config_id = N'5'), N'zh-CN', N'logistics.materials.plant.entities.remark', N'备注', N'Frontend', N'page', 24, N'admin', GETDATE(), 0)
  ,(2046836338984095899, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-TW' AND is_deleted = 0 AND config_id = N'5'), N'zh-TW', N'logistics.materials.plant.entities.remark', N'备注', N'Frontend', N'page', 24, N'admin', GETDATE(), 0)
  ,(2046836338984095900, '5', (SELECT TOP 1 id FROM Takt_Routine_Dev.dbo.takt_routine_i18n_language WHERE culture_code = N'zh-HK' AND is_deleted = 0 AND config_id = N'5'), N'zh-HK', N'logistics.materials.plant.entities.remark', N'备注', N'Frontend', N'page', 24, N'admin', GETDATE(), 0)
;
